//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov_A
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявки.
    /// </summary>
    // *** Start programmer edit section *** (Заявки CustomAttributes)

    // *** End programmer edit section *** (Заявки CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкиE", new string[] {
            "НомерЗаявки as \'Номер заявки\'",
            "ДатаЗаявки as \'Дата заявки\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Клиенты.Наименование"})]
    [AssociatedDetailViewAttribute("ЗаявкиE", "ТчЗаявка", "ТчЗаявкаE", true, "", "Тч заявка", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаявкиE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ЗаявкиL", new string[] {
            "НомерЗаявки as \'Номер заявки\'",
            "ДатаЗаявки as \'Дата заявки\'",
            "Клиенты.Наименование as \'Наименование\'"})]
    public class Заявки : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЗаявки;
        
        private System.DateTime fДатаЗаявки;
        
        private IIS.Kursovaya_Gladkov_A.Клиенты fКлиенты;
        
        private IIS.Kursovaya_Gladkov_A.DetailArrayOfТчЗаявка fТчЗаявка;
        
        // *** Start programmer edit section *** (Заявки CustomMembers)

        // *** End programmer edit section *** (Заявки CustomMembers)

        
        /// <summary>
        /// ДатаЗаявки.
        /// </summary>
        // *** Start programmer edit section *** (Заявки.ДатаЗаявки CustomAttributes)

        // *** End programmer edit section *** (Заявки.ДатаЗаявки CustomAttributes)
        public virtual System.DateTime ДатаЗаявки
        {
            get
            {
                // *** Start programmer edit section *** (Заявки.ДатаЗаявки Get start)

                // *** End programmer edit section *** (Заявки.ДатаЗаявки Get start)
                System.DateTime result = this.fДатаЗаявки;
                // *** Start programmer edit section *** (Заявки.ДатаЗаявки Get end)

                // *** End programmer edit section *** (Заявки.ДатаЗаявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявки.ДатаЗаявки Set start)

                // *** End programmer edit section *** (Заявки.ДатаЗаявки Set start)
                this.fДатаЗаявки = value;
                // *** Start programmer edit section *** (Заявки.ДатаЗаявки Set end)

                // *** End programmer edit section *** (Заявки.ДатаЗаявки Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаявки.
        /// </summary>
        // *** Start programmer edit section *** (Заявки.НомерЗаявки CustomAttributes)

        // *** End programmer edit section *** (Заявки.НомерЗаявки CustomAttributes)
        public virtual int НомерЗаявки
        {
            get
            {
                // *** Start programmer edit section *** (Заявки.НомерЗаявки Get start)

                // *** End programmer edit section *** (Заявки.НомерЗаявки Get start)
                int result = this.fНомерЗаявки;
                // *** Start programmer edit section *** (Заявки.НомерЗаявки Get end)

                // *** End programmer edit section *** (Заявки.НомерЗаявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявки.НомерЗаявки Set start)

                // *** End programmer edit section *** (Заявки.НомерЗаявки Set start)
                this.fНомерЗаявки = value;
                // *** Start programmer edit section *** (Заявки.НомерЗаявки Set end)

                // *** End programmer edit section *** (Заявки.НомерЗаявки Set end)
            }
        }
        
        /// <summary>
        /// Заявки.
        /// </summary>
        // *** Start programmer edit section *** (Заявки.Клиенты CustomAttributes)

        // *** End programmer edit section *** (Заявки.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov_A.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (Заявки.Клиенты Get start)

                // *** End programmer edit section *** (Заявки.Клиенты Get start)
                IIS.Kursovaya_Gladkov_A.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (Заявки.Клиенты Get end)

                // *** End programmer edit section *** (Заявки.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявки.Клиенты Set start)

                // *** End programmer edit section *** (Заявки.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (Заявки.Клиенты Set end)

                // *** End programmer edit section *** (Заявки.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Заявки.
        /// </summary>
        // *** Start programmer edit section *** (Заявки.ТчЗаявка CustomAttributes)

        // *** End programmer edit section *** (Заявки.ТчЗаявка CustomAttributes)
        public virtual IIS.Kursovaya_Gladkov_A.DetailArrayOfТчЗаявка ТчЗаявка
        {
            get
            {
                // *** Start programmer edit section *** (Заявки.ТчЗаявка Get start)

                // *** End programmer edit section *** (Заявки.ТчЗаявка Get start)
                if ((this.fТчЗаявка == null))
                {
                    this.fТчЗаявка = new IIS.Kursovaya_Gladkov_A.DetailArrayOfТчЗаявка(this);
                }
                IIS.Kursovaya_Gladkov_A.DetailArrayOfТчЗаявка result = this.fТчЗаявка;
                // *** Start programmer edit section *** (Заявки.ТчЗаявка Get end)

                // *** End programmer edit section *** (Заявки.ТчЗаявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заявки.ТчЗаявка Set start)

                // *** End programmer edit section *** (Заявки.ТчЗаявка Set start)
                this.fТчЗаявка = value;
                // *** Start programmer edit section *** (Заявки.ТчЗаявка Set end)

                // *** End programmer edit section *** (Заявки.ТчЗаявка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкиE", typeof(IIS.Kursovaya_Gladkov_A.Заявки));
                }
            }
            
            /// <summary>
            /// "ЗаявкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкиL", typeof(IIS.Kursovaya_Gladkov_A.Заявки));
                }
            }
        }
    }
}
