//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov_A
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (Оборудование CustomAttributes)

    // *** End programmer edit section *** (Оборудование CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОборудованиеE", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "Состояние as \'Состояние\'"})]
    [View("ОборудованиеL", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "Состояние as \'Состояние\'"})]
    public class Оборудование : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНаименование;
        
        private IIS.Kursovaya_Gladkov_A.Состояние fСостояние;
        
        // *** Start programmer edit section *** (Оборудование CustomMembers)

        // *** End programmer edit section *** (Оборудование CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.ID CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.ID Get start)

                // *** End programmer edit section *** (Оборудование.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Оборудование.ID Get end)

                // *** End programmer edit section *** (Оборудование.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.ID Set start)

                // *** End programmer edit section *** (Оборудование.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Оборудование.ID Set end)

                // *** End programmer edit section *** (Оборудование.ID Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Наименование CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Наименование Get start)

                // *** End programmer edit section *** (Оборудование.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Оборудование.Наименование Get end)

                // *** End programmer edit section *** (Оборудование.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Наименование Set start)

                // *** End programmer edit section *** (Оборудование.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Оборудование.Наименование Set end)

                // *** End programmer edit section *** (Оборудование.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Состояние CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Состояние CustomAttributes)
        public virtual IIS.Kursovaya_Gladkov_A.Состояние Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Состояние Get start)

                // *** End programmer edit section *** (Оборудование.Состояние Get start)
                IIS.Kursovaya_Gladkov_A.Состояние result = this.fСостояние;
                // *** Start programmer edit section *** (Оборудование.Состояние Get end)

                // *** End programmer edit section *** (Оборудование.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Состояние Set start)

                // *** End programmer edit section *** (Оборудование.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Оборудование.Состояние Set end)

                // *** End programmer edit section *** (Оборудование.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОборудованиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеE", typeof(IIS.Kursovaya_Gladkov_A.Оборудование));
                }
            }
            
            /// <summary>
            /// "ОборудованиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеL", typeof(IIS.Kursovaya_Gladkov_A.Оборудование));
                }
            }
        }
    }
}
