//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov_A
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тех карта.
    /// </summary>
    // *** Start programmer edit section *** (ТехКарта CustomAttributes)

    // *** End programmer edit section *** (ТехКарта CustomAttributes)
    [AutoAltered()]
    [Caption("Техническая карта")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТехКартаE", new string[] {
            "НомерКарты as \'Номер карты\'",
            "Дата as \'Дата\'",
            "Чертеж as \'Чертеж\'",
            "Чертеж.НомерЧертежа as \'Номер чертежа\'",
            "Чертеж.ТчЗаявка.Материалы",
            "Оборудование as \'Оборудование\'",
            "Оборудование.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Чертеж.НомерЧертежа",
            "Чертеж.ТчЗаявка.Материалы",
            "Оборудование.Наименование"})]
    [MasterViewDefineAttribute("ТехКартаE", "Чертеж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЧертежа")]
    [MasterViewDefineAttribute("ТехКартаE", "Оборудование", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ТехКартаL", new string[] {
            "НомерКарты as \'Номер карты\'",
            "Дата as \'Дата\'",
            "Чертеж.НомерЧертежа as \'Номер чертежа\'",
            "Оборудование.Наименование as \'Наименование\'",
            "Чертеж.ТчЗаявка.Материалы.Наименование"})]
    public class ТехКарта : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКарты;
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya_Gladkov_A.Чертеж fЧертеж;
        
        private IIS.Kursovaya_Gladkov_A.Оборудование fОборудование;
        
        // *** Start programmer edit section *** (ТехКарта CustomMembers)

        // *** End programmer edit section *** (ТехКарта CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарта.Дата CustomAttributes)

        // *** End programmer edit section *** (ТехКарта.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарта.Дата Get start)

                // *** End programmer edit section *** (ТехКарта.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ТехКарта.Дата Get end)

                // *** End programmer edit section *** (ТехКарта.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарта.Дата Set start)

                // *** End programmer edit section *** (ТехКарта.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ТехКарта.Дата Set end)

                // *** End programmer edit section *** (ТехКарта.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерКарты.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарта.НомерКарты CustomAttributes)

        // *** End programmer edit section *** (ТехКарта.НомерКарты CustomAttributes)
        public virtual int НомерКарты
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарта.НомерКарты Get start)

                // *** End programmer edit section *** (ТехКарта.НомерКарты Get start)
                int result = this.fНомерКарты;
                // *** Start programmer edit section *** (ТехКарта.НомерКарты Get end)

                // *** End programmer edit section *** (ТехКарта.НомерКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарта.НомерКарты Set start)

                // *** End programmer edit section *** (ТехКарта.НомерКарты Set start)
                this.fНомерКарты = value;
                // *** Start programmer edit section *** (ТехКарта.НомерКарты Set end)

                // *** End programmer edit section *** (ТехКарта.НомерКарты Set end)
            }
        }
        
        /// <summary>
        /// Тех карта.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарта.Оборудование CustomAttributes)

        // *** End programmer edit section *** (ТехКарта.Оборудование CustomAttributes)
        [PropertyStorage(new string[] {
                "Оборудование"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov_A.Оборудование Оборудование
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарта.Оборудование Get start)

                // *** End programmer edit section *** (ТехКарта.Оборудование Get start)
                IIS.Kursovaya_Gladkov_A.Оборудование result = this.fОборудование;
                // *** Start programmer edit section *** (ТехКарта.Оборудование Get end)

                // *** End programmer edit section *** (ТехКарта.Оборудование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарта.Оборудование Set start)

                // *** End programmer edit section *** (ТехКарта.Оборудование Set start)
                this.fОборудование = value;
                // *** Start programmer edit section *** (ТехКарта.Оборудование Set end)

                // *** End programmer edit section *** (ТехКарта.Оборудование Set end)
            }
        }
        
        /// <summary>
        /// Тех карта.
        /// </summary>
        // *** Start programmer edit section *** (ТехКарта.Чертеж CustomAttributes)

        // *** End programmer edit section *** (ТехКарта.Чертеж CustomAttributes)
        [PropertyStorage(new string[] {
                "Чертеж"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov_A.Чертеж Чертеж
        {
            get
            {
                // *** Start programmer edit section *** (ТехКарта.Чертеж Get start)

                // *** End programmer edit section *** (ТехКарта.Чертеж Get start)
                IIS.Kursovaya_Gladkov_A.Чертеж result = this.fЧертеж;
                // *** Start programmer edit section *** (ТехКарта.Чертеж Get end)

                // *** End programmer edit section *** (ТехКарта.Чертеж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТехКарта.Чертеж Set start)

                // *** End programmer edit section *** (ТехКарта.Чертеж Set start)
                this.fЧертеж = value;
                // *** Start programmer edit section *** (ТехКарта.Чертеж Set end)

                // *** End programmer edit section *** (ТехКарта.Чертеж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТехКартаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТехКартаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТехКартаE", typeof(IIS.Kursovaya_Gladkov_A.ТехКарта));
                }
            }
            
            /// <summary>
            /// "ТехКартаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТехКартаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТехКартаL", typeof(IIS.Kursovaya_Gladkov_A.ТехКарта));
                }
            }
        }
    }
}
