//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov_A
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч заявка.
    /// </summary>
    // *** Start programmer edit section *** (ТчЗаявка CustomAttributes)

    // *** End programmer edit section *** (ТчЗаявка CustomAttributes)
    [AutoAltered()]
    [Caption("Тч заявка")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчЗаявкаE", new string[] {
            "НомерДетали as \'Номер детали\'",
            "НаименДетали as \'Наимен детали\'",
            "Количество as \'Количество\'",
            "Цена as \'Цена\'",
            "Материалы as \'Материалы\'",
            "Материалы.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Материалы.Наименование"})]
    [MasterViewDefineAttribute("ТчЗаявкаE", "Материалы", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ТчЗаявка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерДетали;
        
        private string fНаименДетали;
        
        private int fКоличество;
        
        private float fЦена;
        
        private IIS.Kursovaya_Gladkov_A.Материалы fМатериалы;
        
        private IIS.Kursovaya_Gladkov_A.Заявки fЗаявки;
        
        // *** Start programmer edit section *** (ТчЗаявка CustomMembers)

        // *** End programmer edit section *** (ТчЗаявка CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗаявка.Количество CustomAttributes)

        // *** End programmer edit section *** (ТчЗаявка.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗаявка.Количество Get start)

                // *** End programmer edit section *** (ТчЗаявка.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТчЗаявка.Количество Get end)

                // *** End programmer edit section *** (ТчЗаявка.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗаявка.Количество Set start)

                // *** End programmer edit section *** (ТчЗаявка.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТчЗаявка.Количество Set end)

                // *** End programmer edit section *** (ТчЗаявка.Количество Set end)
            }
        }
        
        /// <summary>
        /// НаименДетали.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗаявка.НаименДетали CustomAttributes)

        // *** End programmer edit section *** (ТчЗаявка.НаименДетали CustomAttributes)
        [StrLen(255)]
        public virtual string НаименДетали
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗаявка.НаименДетали Get start)

                // *** End programmer edit section *** (ТчЗаявка.НаименДетали Get start)
                string result = this.fНаименДетали;
                // *** Start programmer edit section *** (ТчЗаявка.НаименДетали Get end)

                // *** End programmer edit section *** (ТчЗаявка.НаименДетали Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗаявка.НаименДетали Set start)

                // *** End programmer edit section *** (ТчЗаявка.НаименДетали Set start)
                this.fНаименДетали = value;
                // *** Start programmer edit section *** (ТчЗаявка.НаименДетали Set end)

                // *** End programmer edit section *** (ТчЗаявка.НаименДетали Set end)
            }
        }
        
        /// <summary>
        /// НомерДетали.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗаявка.НомерДетали CustomAttributes)

        // *** End programmer edit section *** (ТчЗаявка.НомерДетали CustomAttributes)
        public virtual int НомерДетали
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗаявка.НомерДетали Get start)

                // *** End programmer edit section *** (ТчЗаявка.НомерДетали Get start)
                int result = this.fНомерДетали;
                // *** Start programmer edit section *** (ТчЗаявка.НомерДетали Get end)

                // *** End programmer edit section *** (ТчЗаявка.НомерДетали Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗаявка.НомерДетали Set start)

                // *** End programmer edit section *** (ТчЗаявка.НомерДетали Set start)
                this.fНомерДетали = value;
                // *** Start programmer edit section *** (ТчЗаявка.НомерДетали Set end)

                // *** End programmer edit section *** (ТчЗаявка.НомерДетали Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗаявка.Цена CustomAttributes)

        // *** End programmer edit section *** (ТчЗаявка.Цена CustomAttributes)
        public virtual float Цена
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗаявка.Цена Get start)

                // *** End programmer edit section *** (ТчЗаявка.Цена Get start)
                float result = this.fЦена;
                // *** Start programmer edit section *** (ТчЗаявка.Цена Get end)

                // *** End programmer edit section *** (ТчЗаявка.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗаявка.Цена Set start)

                // *** End programmer edit section *** (ТчЗаявка.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ТчЗаявка.Цена Set end)

                // *** End programmer edit section *** (ТчЗаявка.Цена Set end)
            }
        }
        
        /// <summary>
        /// Тч заявка.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗаявка.Материалы CustomAttributes)

        // *** End programmer edit section *** (ТчЗаявка.Материалы CustomAttributes)
        [PropertyStorage(new string[] {
                "Материалы"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov_A.Материалы Материалы
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗаявка.Материалы Get start)

                // *** End programmer edit section *** (ТчЗаявка.Материалы Get start)
                IIS.Kursovaya_Gladkov_A.Материалы result = this.fМатериалы;
                // *** Start programmer edit section *** (ТчЗаявка.Материалы Get end)

                // *** End programmer edit section *** (ТчЗаявка.Материалы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗаявка.Материалы Set start)

                // *** End programmer edit section *** (ТчЗаявка.Материалы Set start)
                this.fМатериалы = value;
                // *** Start programmer edit section *** (ТчЗаявка.Материалы Set end)

                // *** End programmer edit section *** (ТчЗаявка.Материалы Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya_Gladkov_A.Заявки.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗаявка.Заявки CustomAttributes)

        // *** End programmer edit section *** (ТчЗаявка.Заявки CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заявки"})]
        public virtual IIS.Kursovaya_Gladkov_A.Заявки Заявки
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗаявка.Заявки Get start)

                // *** End programmer edit section *** (ТчЗаявка.Заявки Get start)
                IIS.Kursovaya_Gladkov_A.Заявки result = this.fЗаявки;
                // *** Start programmer edit section *** (ТчЗаявка.Заявки Get end)

                // *** End programmer edit section *** (ТчЗаявка.Заявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗаявка.Заявки Set start)

                // *** End programmer edit section *** (ТчЗаявка.Заявки Set start)
                this.fЗаявки = value;
                // *** Start programmer edit section *** (ТчЗаявка.Заявки Set end)

                // *** End programmer edit section *** (ТчЗаявка.Заявки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчЗаявкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчЗаявкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчЗаявкаE", typeof(IIS.Kursovaya_Gladkov_A.ТчЗаявка));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчЗаявка.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчЗаявка CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчЗаявка CustomAttributes)
    public class DetailArrayOfТчЗаявка : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya_Gladkov_A.DetailArrayOfТчЗаявка members)

        // *** End programmer edit section *** (IIS.Kursovaya_Gladkov_A.DetailArrayOfТчЗаявка members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчЗаявка by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчЗаявка.
        /// </summary>
        public DetailArrayOfТчЗаявка(IIS.Kursovaya_Gladkov_A.Заявки fЗаявки) : 
                base(typeof(ТчЗаявка), ((ICSSoft.STORMNET.DataObject)(fЗаявки)))
        {
        }
        
        public IIS.Kursovaya_Gladkov_A.ТчЗаявка this[int index]
        {
            get
            {
                return ((IIS.Kursovaya_Gladkov_A.ТчЗаявка)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya_Gladkov_A.ТчЗаявка dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
