//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov_A
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Чертеж.
    /// </summary>
    // *** Start programmer edit section *** (Чертеж CustomAttributes)

    // *** End programmer edit section *** (Чертеж CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЧертежE", new string[] {
            "НомерЧертежа as \'Номер чертежа\'",
            "Дата as \'Дата\'",
            "ТчЗаявка.НаименДетали as \'Деталь просто\'",
            "ТчЗаявка.Материалы as \'Материал просто\'",
            "Утверждение as \'Утверждение\'"})]
    [View("ЧертежL", new string[] {
            "НомерЧертежа as \'Номер чертежа\'",
            "Дата as \'Дата\'",
            "Утверждение as \'Утверждение\'",
            "ТчЗаявка.НаименДетали as \'Наимен детали\'",
            "ТчЗаявка.Материалы"})]
    public class Чертеж : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЧертежа;
        
        private System.DateTime fДата;
        
        private bool fУтверждение;
        
        private IIS.Kursovaya_Gladkov_A.ТчЗаявка fТчЗаявка;
        
        // *** Start programmer edit section *** (Чертеж CustomMembers)

        // *** End programmer edit section *** (Чертеж CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Чертеж.Дата CustomAttributes)

        // *** End programmer edit section *** (Чертеж.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Чертеж.Дата Get start)

                // *** End programmer edit section *** (Чертеж.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Чертеж.Дата Get end)

                // *** End programmer edit section *** (Чертеж.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертеж.Дата Set start)

                // *** End programmer edit section *** (Чертеж.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Чертеж.Дата Set end)

                // *** End programmer edit section *** (Чертеж.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерЧертежа.
        /// </summary>
        // *** Start programmer edit section *** (Чертеж.НомерЧертежа CustomAttributes)

        // *** End programmer edit section *** (Чертеж.НомерЧертежа CustomAttributes)
        public virtual int НомерЧертежа
        {
            get
            {
                // *** Start programmer edit section *** (Чертеж.НомерЧертежа Get start)

                // *** End programmer edit section *** (Чертеж.НомерЧертежа Get start)
                int result = this.fНомерЧертежа;
                // *** Start programmer edit section *** (Чертеж.НомерЧертежа Get end)

                // *** End programmer edit section *** (Чертеж.НомерЧертежа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертеж.НомерЧертежа Set start)

                // *** End programmer edit section *** (Чертеж.НомерЧертежа Set start)
                this.fНомерЧертежа = value;
                // *** Start programmer edit section *** (Чертеж.НомерЧертежа Set end)

                // *** End programmer edit section *** (Чертеж.НомерЧертежа Set end)
            }
        }
        
        /// <summary>
        /// Утверждение.
        /// </summary>
        // *** Start programmer edit section *** (Чертеж.Утверждение CustomAttributes)

        // *** End programmer edit section *** (Чертеж.Утверждение CustomAttributes)
        public virtual bool Утверждение
        {
            get
            {
                // *** Start programmer edit section *** (Чертеж.Утверждение Get start)

                // *** End programmer edit section *** (Чертеж.Утверждение Get start)
                bool result = this.fУтверждение;
                // *** Start programmer edit section *** (Чертеж.Утверждение Get end)

                // *** End programmer edit section *** (Чертеж.Утверждение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертеж.Утверждение Set start)

                // *** End programmer edit section *** (Чертеж.Утверждение Set start)
                this.fУтверждение = value;
                // *** Start programmer edit section *** (Чертеж.Утверждение Set end)

                // *** End programmer edit section *** (Чертеж.Утверждение Set end)
            }
        }
        
        /// <summary>
        /// Чертеж.
        /// </summary>
        // *** Start programmer edit section *** (Чертеж.ТчЗаявка CustomAttributes)

        // *** End programmer edit section *** (Чертеж.ТчЗаявка CustomAttributes)
        [PropertyStorage(new string[] {
                "ТчЗаявка"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov_A.ТчЗаявка ТчЗаявка
        {
            get
            {
                // *** Start programmer edit section *** (Чертеж.ТчЗаявка Get start)

                // *** End programmer edit section *** (Чертеж.ТчЗаявка Get start)
                IIS.Kursovaya_Gladkov_A.ТчЗаявка result = this.fТчЗаявка;
                // *** Start programmer edit section *** (Чертеж.ТчЗаявка Get end)

                // *** End programmer edit section *** (Чертеж.ТчЗаявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Чертеж.ТчЗаявка Set start)

                // *** End programmer edit section *** (Чертеж.ТчЗаявка Set start)
                this.fТчЗаявка = value;
                // *** Start programmer edit section *** (Чертеж.ТчЗаявка Set end)

                // *** End programmer edit section *** (Чертеж.ТчЗаявка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЧертежE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧертежE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧертежE", typeof(IIS.Kursovaya_Gladkov_A.Чертеж));
                }
            }
            
            /// <summary>
            /// "ЧертежL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЧертежL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЧертежL", typeof(IIS.Kursovaya_Gladkov_A.Чертеж));
                }
            }
        }
    }
}
